grails-app/domain/fr/isima/Post.groovy
package fr.isima

class Post {

    Date creationDate
    String content
    Date lastEditionDate
    Thread thread

    static belongsTo = [author:User]
    static hasMany = [posts:Post, votes:Vote]
    static hasOne = [post:Post]

    def getCountingVote() {
        if(votes == null)
            return 0
        return votes.size() - 2 * votes.count {!it.up}
    }

    static mapping = {
        content type:'text'
    }

    static constraints = {
        thread(nullable:true,validator: {val, obj ->
            return (obj.thread != obj.post)
        })
        content null:false, blank:false, minSize: 1
    }
}

grails-app/domain/fr/isima/Thread.groovy
package fr.isima

class Thread {

    String title
    int viewCount
    Post firstPost

    def getPostsToShow() {
        posts.sort(new Comparator<Post>() {
            @Override
            int compare(Post o1, Post o2) {
                if(o1.countingVote == o2.countingVote)
                    return o1.creationDate.compareTo(o2.creationDate)
                return 0 - (o1.countingVote.compareTo(o2.countingVote))
            }
        })
    }


    static hasMany = [tags:Tag, posts:Post]
    static belongsTo = Tag

    static mapping = {
        title type:'text'
    }

    static constraints = {
        title blank:false
        tags nullable:false, minSize:1
    }
}

grails-app/controllers/fr/isima/PostController.groovy
package fr.isima

import org.springframework.dao.DataIntegrityViolationException

class PostController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def userService
    def postService

    def index() {
        log.info "[POST-index] redirect to home"
        redirect(controller: "home", action: "index", params: params)
    }

    def create() {
        if(!session[userService.USER_SESSION_OBJECT_NAME]) {redirect(controller: "home");return}

        log.info "[POST-create] is called"
        [postInstance: new Post(params)]
    }

    def save() {
        if(!session[userService.USER_SESSION_OBJECT_NAME]) {
            redirect(controller: "home");
            return
        }

        log.info "[POST-save] is called"

        def postInstance = new Post(params)
        postInstance.author = session[userService.USER_SESSION_OBJECT_NAME];
        if (!postInstance.save(flush: true)) {
            log.error "[POST-save] could not save post"
            render(view: "create", model: [postInstance: postInstance])
            return
        }

        log.info "[POST-save] post created, redirect to post view"
        flash.message = message(code: 'default.created.message', args: [message(code: 'post.entityName.label', default: 'Post'), postInstance.id])
        redirect(action: "show", controller: "thread", id: (postInstance.thread ? postInstance.thread.id : postInstance.post.thread.id))
    }

    def show(Long id) {
        log.info "[POST-show] is called"

        def postInstance
        if(id)
            postInstance = postService.getPostById(id)
        if (!postInstance) {
            log.warn "[POST-show] post not found"
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'post.entityName.label', default: 'Post'), id])
            redirect(action: "index", controller: "home")
            return
        }

        [postInstance: postInstance]
    }

    def edit(Long id) {
        log.info "[POST-edit] is called for post ${id}"
        if(!session[userService.USER_SESSION_OBJECT_NAME]) {redirect(controller: "home");return}

        def postInstance = null
        if(id)
            postInstance = postService.getPostById(id)
        if (!postInstance) {
            log.warn "[POST-edit] post not found"
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'post.entityName.label', default: 'Post'), id])
            redirect(action: "index", controller: "home")
            return
        }

        def userConnected = session[userService.USER_SESSION_OBJECT_NAME]
        def isAdmin = (userConnected.rank == Rank.Administrator)

        if(userConnected.id != postInstance.author.id && !isAdmin)
            redirect(controller: "home")

        [postInstance: postInstance, threadInstance: postInstance.thread, isAdmin: isAdmin]
    }

    def update(Long id, Long version) {
        if(!session[userService.USER_SESSION_OBJECT_NAME]) {redirect(controller: "home");return}

        def postInstance = postService.getPostById(id)
        log.info "[POST-update] is called for post ${id}"
        if (!postInstance) {
            log.warn "[POST-update] post ${id} not found"
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'post.entityName.label', default: 'Post'), id])
            redirect(action: "index")
            return
        }

        def userConnected = session[userService.USER_SESSION_OBJECT_NAME]
        def isAdmin = (userConnected.rank == Rank.Administrator)

        if(userConnected.id != postInstance.author.id && !isAdmin)
            redirect(controller: "home")

        if (version != null) {
            if (postInstance.version > version) {
                postInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                        [message(code: 'post.entityName.label', default: 'Post')] as Object[],
                        "Another user has updated this Post while you were editing")
                render(view: "edit", model: [postInstance: postInstance])
                return
            }
        }

        postInstance.content = params.get("content")

        if (!postService.update(postInstance)) {
            log.error "[POST-update] could not update post " + postInstance.id
            render(view: "edit", model: [postInstance: postInstance])
            return
        }

        log.info "[POST-update] post ${postInstance} updated"

        flash.message = message(code: 'default.updated.message', args: [message(code: 'post.entityName.label', default: 'Post'), postInstance.id])
        redirect(action: "show", controller: "thread", id: (postInstance.thread ? postInstance.thread.id : postInstance.post.thread.id))
    }

    def delete(Long id) {
        if(!session[userService.USER_SESSION_OBJECT_NAME]) redirect(controller: "home")

        def postInstance = null
        if(id)
            postInstance = postService.getPostById(id)
        if (!postInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'post.entityName.label', default: 'Post'), id])
            redirect(action: "index")
            return
        }

        try {
            postInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'post.entityName.label', default: 'Post'), id])
            redirect(action: "index")
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'post.entityName.label', default: 'Post'), id])
            redirect(action: "show", id: id)
        }
    }
}

grails-app/views/post/_comment.gsp
<%@ page import="fr.isima.Post" %>

<g:hiddenField id="thread" name="thread.id" value="${threadInstance.id}" />

<div class="form-group ${hasErrors(bean: postInstance, field: 'content', 'error')} ">
    <g:textArea id="comment-editor" class="form-control" name="content" value="${postInstance?.content}" rows="5" cols="40" placeholder="${message(code: 'post.content.placeholder', default: 'post.content.placeholder')}" />
</div>

grails-app/views/post/_form.gsp
<%@ page import="fr.isima.Post" %>

<g:hiddenField id="thread" name="thread.id" value="${threadInstance.id}" />

<div class="form-group ${hasErrors(bean: postInstance, field: 'content', 'error')} ">
    <label for="content">
        <h3><g:message for="post-editor" code="thread.answer.create.label" default="Answer" /></h3>
    </label>
    <g:textArea id="post-editor" class="form-control" name="content" value="${postInstance?.content}" rows="30" cols="50" placeholder="${message(code: 'post.content.placeholder', default: 'post.content.placeholder')}" />
</div>

grails-app/views/post/_showPost.gsp
<g:if test="${currentPost}">

    <div class="well well-lg" style="position:relative;">
        <g:if test="${isAdmin || currentPost.author.id == userConnected?.id}" >
            <g:link class="btn btn-default btn-sm" style="position:absolute; top:0; right:0;" action="edit" controller="post" id="${currentPost.id}">
                <span class="glyphicon glyphicon-pencil"></span>
            </g:link>
        </g:if>

        <div class="col-md-1">

            <div id="vote" class="text-center" name="vote">
                <g:formRemote name="voteUpForm" url="[controller:'vote', action:'addVote']" method="GET" update="resultAddingVote${currentPost.id}">
                    <g:hiddenField name="up" value="1"/>
                    <g:hiddenField name="postId" value="${currentPost.id}"/>
                    <button class="btn btn-success btn-sm"><i class="glyphicon glyphicon-chevron-up"></i></button>
                </g:formRemote>
                <div id="resultAddingVote${currentPost.id}">
                    <span id="voteResult">${currentPost.getCountingVote()}</span>
                </div>
                <g:formRemote name="voteDownForm" url="[controller:'vote', action:'addVote']" method="GET" update="resultAddingVote${currentPost.id}">
                    <g:hiddenField name="up" value="0"/>
                    <g:hiddenField name="postId" value="${currentPost.id}"/>
                    <button class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-chevron-down"></i></button>
                </g:formRemote>
            </div>

        </div>
        <div class="col-md-11">

            ${currentPost.content}

            <div class="panel-footer">

                <div class="small pull-left">
                    <div class="property-value" name="creationDate">
                        <g:message code="post.creationDate" />
                        <g:formatDate type="date" style="LONG" locale="true" date="${currentPost.creationDate}"/>
                    </div>
                    <div class="property-value" name="lastEditionDate">
                        <g:message code="post.editionDate" />
                        <g:formatDate type="datetime" style="LONG" timeStyle="SHORT" locale="true" date="${currentPost.lastEditionDate}"/>
                    </div>
                </div>
                <g:set var="currentUser" value="${currentPost.author}" />
                <g:render template="../user/showUser" />

            </div>

        </div>
        <div class="clearfix"></div>

    </div>

    <div style="margin-right:100px;margin-left:100px;" class="">

        <g:each in="${currentPost.posts}" var="comment">
            <blockquote class="blockquote-reverse" style="font-size:0.9em;">
                ${comment.content}
                <footer>${comment.author.displayName}</footer>
            </blockquote>
        </g:each>

        <g:if test="${session['user']}">

            <div id="comment-form-${currentPost.id}" style="display:none;" class="col-md-6 col-md-offset-4">
                <g:form action="saveComment" role="form">
                    <fieldset>
                        <g:hiddenField id="post" name="post.id" value="${currentPost.id}" />
                        <g:render template="../post/comment"/>
                    </fieldset>
                    <fieldset>
                        <g:submitButton name="create" class="save btn btn-default" value="${message(code: 'thread.comment.create', default: 'Create')}" />
                    </fieldset>
                </g:form>
            </div>
            <div class="clearfix"></div>
            <div>
                <a onclick="$(this).hide(); $('#comment-form-${currentPost.id}').show();" class="pull-right" href="#comment-form-${currentPost.id}">${message(code: 'thread.comment.create.label', default: 'Post a comment')}</a>
            </div>

        </g:if>

    </div>

</g:if>

grails-app/views/post/create.gsp
<%@ page import="fr.isima.Post" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'post.entityName.label', default: 'Post')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<%--<a href="#create-post" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>--%>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-post" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${postInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${postInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/post/edit.gsp
<%@ page import="fr.isima.Post" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'post.label', default: 'Post')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<div id="edit-post" class="" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:flashMessage/>
			<g:hasErrors bean="${postInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${postInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${postInstance?.id}" />
				<g:hiddenField name="version" value="${postInstance?.version}" />
				<fieldset class="form">

                    <g:hiddenField id="thread" name="thread.id" value="${threadInstance.id}" />

                    <div class="form-group ${hasErrors(bean: postInstance, field: 'content', 'error')} ">
                        <g:textArea id="post-editor" class="form-control" name="content" value="${postInstance?.content}" rows="30" cols="50" placeholder="${message(code: 'post.content.placeholder', default: 'post.content.placeholder')}" />
                    </div>

				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="btn btn-default" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/post/list.gsp
<%@ page import="fr.isima.Post" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'post.entityName.label', default: 'Post')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<%--<a href="#list-post" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>--%>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-post" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<th><g:message code="post.author.label" default="Author" /></th>
					
						<g:sortableColumn property="content" title="${message(code: 'post.content.label', default: 'Content')}" />
					
						<g:sortableColumn property="creationDate" title="${message(code: 'post.creationDate.label', default: 'Creation Date')}" />
					
						<g:sortableColumn property="lastEditionDate" title="${message(code: 'post.lastEditionDate.label', default: 'Last Edition Date')}" />
					
						<th><g:message code="post.thread.label" default="Thread" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${postInstanceList}" status="i" var="postInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${postInstance.id}">${fieldValue(bean: postInstance, field: "author")}</g:link></td>
					
						<td>${fieldValue(bean: postInstance, field: "content")}</td>
					
						<td><g:formatDate date="${postInstance.creationDate}" /></td>
					
						<td><g:formatDate date="${postInstance.lastEditionDate}" /></td>
					
						<td>${fieldValue(bean: postInstance, field: "thread")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${postInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/post/show.gsp
<%@ page import="fr.isima.Thread" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'thread.entityName.label', default: 'Thread')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>

		<a href="#show-thread" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-thread" class="content scaffold-show" role="main">
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
            <g:hasErrors bean="${postInstance}">
                <ul class="errors" role="alert">
                    <g:eachError bean="${postInstance}" var="error">
                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                    </g:eachError>
                </ul>
            </g:hasErrors>

            <h1><g:fieldValue bean="${threadInstance}" field="title"/></h1><br />
            <span class="property-value" name="viewCount"><g:fieldValue bean="${threadInstance}" field="viewCount"/></span><g:message code="thread.viewCount.label" /><br />
            <g:set var="currentPost" value="${threadInstance.firstPost}" />
            <g:render template="../post/showPost"/>

            <g:each in="${threadInstance.getPostsToShow()}" var="post">
                <g:if test="${post.id != threadInstance.firstPost.id}" >
                    <g:set var="currentPost" value="${post}" />
                    <g:render template="../post/showPost"/>
                </g:if>
            </g:each>

            <g:form action="savePost" style="border: 1px darkgreen dashed" >
                <fieldset class="form">
                    <g:render template="../post/form"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>

			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${threadInstance?.id}" />
					<g:link class="edit" action="edit" id="${threadInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>