grails-app/domain/fr/isima/Post.groovy
package fr.isima

class Post {

    Date creationDate
    String content
    Date lastEditionDate
    Thread thread

    static belongsTo = [author:User]
    static hasMany = [posts:Post, votes:Vote]
    static hasOne = [post:Post]

    def getCountingVote() {
        if(votes == null)
            return 0
        return votes.size() - 2 * votes.count {!it.up}
    }

    static mapping = {
        content type:'text'
    }

    static constraints = {
        thread(nullable:true,validator: {val, obj ->
            return (obj.thread != obj.post)
        })
        content null:false, blank:false, minSize: 1
    }
}

grails-app/domain/fr/isima/Thread.groovy
package fr.isima

class Thread {

    String title
    int viewCount
    Post firstPost

    def getPostsToShow() {
        posts.sort(new Comparator<Post>() {
            @Override
            int compare(Post o1, Post o2) {
                if(o1.countingVote == o2.countingVote)
                    return o1.creationDate.compareTo(o2.creationDate)
                return 0 - (o1.countingVote.compareTo(o2.countingVote))
            }
        })
    }


    static hasMany = [tags:Tag, posts:Post]
    static belongsTo = Tag

    static mapping = {
        title type:'text'
    }

    static constraints = {
        title blank:false
        tags nullable:false, minSize:1
    }
}

grails-app/controllers/fr/isima/ThreadController.groovy
package fr.isima

import org.springframework.dao.DataIntegrityViolationException

class ThreadController {

    def userService
    def threadService
    def tagService
    def postService

    static allowedMethods = [save: "POST",savePost: "POST", update: "POST", delete: "GET"]

    def index() {
        log.info "[THREAD-index] called, redirect to create"
        redirect(action: "create", params: params)
    }

    def create() {
        log.info "[THREAD-create] called"
        if(!session[userService.USER_SESSION_OBJECT_NAME]) {redirect(uri: "/oauth/google/authenticate");return}

        def threadInstance = new Thread(params["thread"])
        if(!threadInstance.tags)
            threadInstance.tags = new HashSet<Tag>()
        [threadInstance: threadInstance, tagsList: tagService.getAllTagsOrderByUse()]
    }

    def save() {
        log.info "[THREAD-save] called"
        if(!session[userService.USER_SESSION_OBJECT_NAME]) {
            redirect(controller: "home");
            return
        }

        def threadInstance = null
        if(!params) {
            render(view: "create", model: [threadInstance: threadInstance])
            return
        }

        def postInstance = new Post(params["post"])
        threadInstance = new Thread(params["thread"])
        threadInstance.firstPost = postInstance
        /*if(!threadInstance.tags)
            threadInstance.tags = new HashSet<Tag>()*/
        postInstance.thread = threadInstance
        def currentDate = new Date(System.currentTimeMillis())
        postInstance.creationDate = currentDate
        postInstance.lastEditionDate = currentDate
        postInstance.author = session[userService.USER_SESSION_OBJECT_NAME];

        /// Les tags sont au format idNum1,idNum2,idNum3...
        def tags = params.get("tag-name-auto")
        if (tags) {
            def list = new ArrayList<Tag>()
            params.get("tag-name-auto")?.split(",")?.each {
                def tag = tagService.getTagById(Long.parseLong(it))
                list.add(tag)
            }
            list.each {
                threadInstance.addToTags(it)
            }
        }
        else
            log.warn "[THREAD-save] tag list is empty"

        if (!threadService.newThread(threadInstance))
        {
            log.error "[THREAD-save] called"
            render(view: "create", model: [threadInstance: threadInstance])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'thread.entityName.label', default: 'Thread'), threadInstance.id])

        redirect(action: "show", id: threadInstance.id)
    }

    def savePost() {
        log.info "[THREAD-savePost] called"
        if(!session[userService.USER_SESSION_OBJECT_NAME]) {redirect(controller: "home");return}

        def threadInstance = threadService.getThreadById(Long.parseLong(params.get("thread.id")))
        def postInstance = new Post()
        postInstance.content = params.get("content")
        postInstance.author = session[userService.USER_SESSION_OBJECT_NAME]
        def currentDate = new Date()
        postInstance.creationDate = currentDate
        postInstance.lastEditionDate = currentDate
        postInstance.post = null
        postInstance.thread = threadInstance

        if (!postService.newPost(postInstance))
        {
            log.error "[THREAD-savePost] post could not be saved"
            render(view: "show", id: threadInstance.id, model: [threadInstance: threadInstance, postInstance: postInstance])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'post.entityName.label', default: 'Post'), postInstance.id])
        redirect(action: "show", id: threadInstance.id)
    }

    def saveComment() {
        log.info "[THREAD-saveComment] called"
        if(!session[userService.USER_SESSION_OBJECT_NAME]) {redirect(controller: "home");return}

        def post = postService.getPostById(Long.parseLong(params.get("post.id")))
        def threadInstance = threadService.getThreadById(Long.parseLong(params.get("thread.id")))

        if (post)
        {

            def commentInstance = new Post()
            commentInstance.content = params.get("content")
            commentInstance.author = session[userService.USER_SESSION_OBJECT_NAME]
            def currentDate = new Date()
            commentInstance.creationDate = currentDate
            commentInstance.lastEditionDate = currentDate
            commentInstance.post = post

            if (!postService.newPost(commentInstance))
            {
                log.error "[THREAD-saveComment] comment could not be saved"
                render(view: "show", id: threadInstance.id, model: [threadInstance: threadInstance, commentInstance: commentInstance])
                return
            }

        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'post.entityName.label', default: 'Post'), post.id])
        redirect(action: "show", id: threadInstance.id)

    }

    def show(Long id) {
        log.info "[THREAD-show] called"
        def threadInstance = null
        if(id)
            threadInstance = threadService.getThreadById(id)
        if (!threadInstance) {
            log.warn "[THREAD-show] thread does not exist"
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'thread.entityName.label', default: 'Thread'), id])
            redirect(action: "index")
            return
        }

        def isEditable = false
        def isAdmin = false
        def userConnected = session[userService.USER_SESSION_OBJECT_NAME]

        if(userConnected) {
            isAdmin = (userConnected.rank == Rank.Administrator)
            isEditable = (isAdmin | (userConnected.id == threadInstance.firstPost.author.id))
        }

        threadService.incrementView(id);
        [threadInstance: threadInstance, isEditable: isEditable, isAdmin: isAdmin, userConnected: userConnected]
    }

    def edit(Long id) {
        log.info "[THREAD-edit] called"
        if(!session[userService.USER_SESSION_OBJECT_NAME]) {
            redirect(controller: "home");
            return
        }

        def threadInstance = null
        if(id)
            threadInstance = threadService.getThreadById(id)

        if (!threadInstance) {
            log.warn "[THREAD-edit] thread does not exist"
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'thread.entityName.label', default: 'Thread'), id])
            redirect(action: "index")
            return
        }

        def userConnected = session[userService.USER_SESSION_OBJECT_NAME]
        def isAdmin = (userConnected.rank == Rank.Administrator)

        if(userConnected.id != threadInstance.firstPost.author.id && !isAdmin) {
            log.warn "[THREAD-edit] user could not edit the thread"
            redirect(controller: "home")
            return
        }

        [threadInstance: threadInstance, tagsEnregistred: threadInstance.tags, tagsList: tagService.getAllTagsOrderByUse(), isAdmin: isAdmin]
    }

    def update(Long id, Long version) {
        log.info "[THREAD-update] called"
        if(!session[userService.USER_SESSION_OBJECT_NAME]) {redirect(controller: "home");return}

        def threadInstance = null
        if(id)
            threadInstance = threadService.getThreadById(id)
        if (!threadInstance) {
            log.warn "[THREAD-update] thread does not exist"
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'thread.entityName.label', default: 'Thread'), id])
            redirect(action: "index")
            return
        }

        def userConnected = session[userService.USER_SESSION_OBJECT_NAME]
        def isAdmin = (userConnected.rank == Rank.Administrator)

        if(userConnected.id != threadInstance.firstPost.author.id && !isAdmin) {
            log.warn "[THREAD-update] user is not allowed to update thread"
            redirect(controller: "home")
        }

        if (version != null) {
            if (threadInstance.version > version) {
                threadInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                        [message(code: 'thread.entityName.label', default: 'Thread')] as Object[],
                        "Another user has updated this Thread while you were editing")
                render(view: "edit", model: [threadInstance: threadInstance])
                return
            }
        }

        /// Les tags sont au format idNum1,idNum2,idNum3...
        def tags = params.get("tag-name-auto")
        if (tags) {
            def list = new ArrayList<Tag>()
            params.get("tag-name-auto")?.split(",")?.each {
                def tag = tagService.getTagById(Long.parseLong(it))
                list.add(tag)
            }
            list.each {
                /// On ajoute uniquement les nouveaux tags
                if(!threadInstance.tags.contains(it))
                    threadInstance.addToTags(it)
            }
        }

        threadInstance.title = params.get("thread.title")
        threadInstance.firstPost.content = params.get("post.content")

        if (!threadService.updateThread(threadInstance)) {
            log.error "[THREAD-update] thread could not be updated"
            render(view: "edit", model: [threadInstance: threadInstance])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'thread.entityName.label', default: 'Thread'), threadInstance.id])
        redirect(action: "show", id: threadInstance.id)
    }

    def delete(Long id) {
        log.info "[THREAD-delete] called"
        if(!session[userService.USER_SESSION_OBJECT_NAME]) {redirect(controller: "home");return}

        def threadInstance = null
        if(id)

grails-app/views/thread/_form.gsp
<%@ page import="fr.isima.Thread" %>

<div class="form-group ${hasErrors(bean: threadInstance, field: 'title', 'error')}">
    <label for="title" class="col-sm-2 control-label">
        <g:message code="thread.title.label" default="Title" />
    </label>
    <div class="col-sm-10">
        <g:textField id="title" name="thread.title" class="form-control" value="${threadInstance?.title}" placeholder="${message(code: 'thread.title.placeholder', default: 'thread.title.placeholder')}" />
    </div>
</div>

<div class="form-group">

    <label for="tag-name-auto" class="col-sm-2 control-label">
        <g:message code="thread.tags.label" default="Tags" />
    </label>
    <div class="col-sm-10">
        <g:textField name="tag-name-auto" class="form-control" value="" placeholder="${message(code: 'thread.tags.placeholder', default: 'thread.tags.placeholder')}" /><br/>
        <g:if test="${tagsEnregistred}" >
            <g:message code="thread.tags.already.enregistred" default="Tags : " />
            <g:each in="${tagsEnregistred}" var="tag">
                ${tag.name}
            </g:each>
        </g:if>
    </div>
</div>

<div class="form-group ${hasErrors(bean: threadInstance?.firstPost, field: 'content', 'error')}">
    <label for="content" class="col-sm-2 control-label">
        <g:message code="post.content.label" default="Content" />
    </label>
    <div class="col-sm-10">
        <g:textArea id="thread-editor" name="post.content">${threadInstance?.firstPost?.content}</g:textArea>
    </div>
</div>

grails-app/views/thread/create.gsp
<%@ page import="fr.isima.Tag; fr.isima.Thread" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
        <g:set var="entityNameThread" value="${message(code: 'thread.entityName.label', default: '')}" />
        <g:set var="entityNameTag" value="${message(code: 'tag.entityName.label', default: '')}" />
		<title><g:message code="default.create.label" args="[entityNameThread]" /></title>
        <link rel="stylesheet" href="${resource(dir: 'css', file: 'token.css')}" type="text/css"/>
        <ckeditor:resources/>
        <g:javascript library="autocomplete"/>
    </head>
	<body>

		<div id="create-thread" class="col-md-9" role="main">

			<h1><g:message code="thread.create.label" args="[entityNameThread]" /></h1>

			<g:flashMessage />

            <g:hasErrors bean="${threadInstance}">
                <div class="alert alert-danger" role="alert">
                    <g:eachError bean="${threadInstance}" var="error">
                        <p><g:message error="${error}"/></p>
                    </g:eachError>
                </div>
            </g:hasErrors>

            <g:hasErrors bean="${threadInstance?.firstPost}">
                <div class="alert alert-danger" role="alert">
                    <g:eachError bean="${threadInstance?.firstPost}" var="error">
                        <p><g:message error="${error}"/></p>
                    </g:eachError>
                </div>
            </g:hasErrors>

            <g:form action="save" class="form-horizontal" role="form">
                <fieldset class="form">

                    <g:render template="form"/>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <g:submitButton name="create" class="save btn btn-default" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                        </div>
                    </div>

                </fieldset>
            </g:form>
		</div>

        <div id="create-tag" class="col-md-3">

            <h1><g:message code="default.create.label" args="[entityNameTag]" /></h1>

            <g:formRemote name="tagAddForm" url="[controller:'tag', action:'insertTag']" update="resultAddingTag">
                <g:render template="../tag/form"/>
                <g:submitButton class="btn btn-default" name="${message(code: 'tag.create.label', default: 'Add Tag')}"/>
            </g:formRemote>
        </div>
	</body>
</html>

grails-app/views/thread/edit.gsp
<%@ page import="fr.isima.Thread" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
        <g:set var="entityNameThread" value="${message(code: 'thread.entityName.label', default: '')}" />
        <g:set var="entityNameTag" value="${message(code: 'tag.entityName.label', default: '')}" />
        <title><g:message code="default.edit.label" args="[entityNameThread]" /></title>
        <ckeditor:resources/>
        <link rel="stylesheet" href="${resource(dir: 'css', file: 'token.css')}" type="text/css"/>
        <g:javascript library="autocomplete"/>
	</head>
	<body>
		<div id="edit-thread" class="" role="main">
			<h1><g:message code="default.edit.label" args="[entityNameThread]" /></h1>
			<g:if test="${flash.message}">
			    <div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${threadInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${threadInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${threadInstance?.id}" />
				<g:hiddenField name="version" value="${threadInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
                <fieldset class="buttons">
                    <g:actionSubmit class="btn btn-default" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/thread/list.gsp
<%@ page import="fr.isima.Thread" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'thread.label', default: 'Thread')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-thread" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-thread" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<g:sortableColumn property="title" title="${message(code: 'thread.title.label', default: 'Title')}" />
					
						<g:sortableColumn property="viewCount" title="${message(code: 'thread.viewCount.label', default: 'View Count')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${threadInstanceList}" status="i" var="threadInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${threadInstance.id}">${fieldValue(bean: threadInstance, field: "title")}</g:link></td>
					
						<td>${fieldValue(bean: threadInstance, field: "viewCount")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${threadInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/thread/show.gsp
<%@ page import="fr.isima.Thread" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'thread.entityName.label', default: 'Thread')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>

        <div id="show-thread" role="main">
            <g:flashMessage />

            <g:hasErrors bean="${postInstance}">
                <ul class="errors" role="alert">
                    <g:eachError bean="${postInstance}" var="error">
                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                    </g:eachError>
                </ul>
            </g:hasErrors>

            <div>
            <h1 class="pull-left">
                <g:fieldValue bean="${threadInstance}" field="title"/>
                <small><g:fieldValue bean="${threadInstance}" field="viewCount"/> <g:message code="thread.viewCount.label" /></small>
            </h1>
            <g:if test="${isEditable}" >
                <div class="btn-group pull-right" style="margin-top:20px;">
                    <g:link class="btn btn-default btn-sm" action="edit" id="${threadInstance.id}"><span class="glyphicon glyphicon-pencil"></span></g:link>

                </div>
            </g:if>
            </div>

            <div class="clearfix"></div>

            <div class="btn-group" style="top:2px;left:4px;">
                <g:each in="${threadInstance.tags}" var="tag">

                    <g:link class="btn btn-success btn-xs" action="show" controller="tag" id="${tag.id}">
                        ${tag.name}
                    </g:link>

                </g:each>
            </div>

            <g:set var="currentPost" value="${threadInstance.firstPost}" />
            <g:render template="../post/showPost"/>
            
            <g:each in="${threadInstance.getPostsToShow()}" var="post">

                <g:if test="${post.id != threadInstance.firstPost.id}" >
                    <g:set var="currentPost" value="${post}" />
                    <g:render template="../post/showPost"/>
                </g:if>

            </g:each>


            <g:if test="${session['user']}">
                <g:form action="savePost" role="form" style="margin-left:100px;">
                    <fieldset>
                        <g:render template="../post/form"/>
                    </fieldset>
                    <fieldset>
                        <g:submitButton name="create" class="save btn btn-default" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                    </fieldset>
                </g:form>
            </g:if>
		</div>
	</body>
</html>