grails-app/domain/fr/isima/Tag.groovy
package fr.isima

class Tag {

    String name

    static hasMany = [threads:Thread]

    static constraints = {
        name blank: false, unique:true
    }
}

grails-app/domain/fr/isima/Thread.groovy
package fr.isima

class Thread {

    String title
    int viewCount
    Post firstPost

    def getPostsToShow() {
        posts.sort(new Comparator<Post>() {
            @Override
            int compare(Post o1, Post o2) {
                if(o1.countingVote == o2.countingVote)
                    return o1.creationDate.compareTo(o2.creationDate)
                return 0 - (o1.countingVote.compareTo(o2.countingVote))
            }
        })
    }


    static hasMany = [tags:Tag, posts:Post]
    static belongsTo = Tag

    static mapping = {
        title type:'text'
    }

    static constraints = {
        title blank:false
        tags nullable:false, minSize:1
    }
}

grails-app/controllers/fr/isima/HomeController.groovy
package fr.isima

class HomeController {

    def threadService
    def tagService

    def index() {

        log.info "[HOME-index]"

        [threads: threadService.threads(), tags: tagService.getAllTagsOrderByUse()]

    }

    def error404() {
        log.info "[HOME-404] called"
    }
}

grails-app/views/home/error404.gsp
<%--
  Created by IntelliJ IDEA.
  User: alexandre
  Date: 15/01/2014
  Time: 15:45
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title></title>
</head>

<body>
<div class="row text-center">
    <img src="${resource(dir: "images", file: "404.png")}" alt="" />
</div>
</body>
</html>

grails-app/views/home/index.gsp
<%--
  Created by IntelliJ IDEA.
  User: alexandre
  Date: 15/01/2014
  Time: 15:45
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title></title>
</head>

<body>

<g:jumbotron />

<g:flashMessage/>
<div class="row">
</div>
<div class="row">
    <div class="col-md-8">
        <div class="">
            <h1>${message(code: 'home.threadList.label', default: 'Last Question')}</h1>
        </div>
        <g:each in="${threads}" status="i" var="threadInstance">
            <div class="well" style="padding:0 0 0 20px;">
                <blockquote style="margin-bottom:0;">
                    <g:link controller="thread" action="show" id="${threadInstance.id}">${fieldValue(bean: threadInstance, field: "title")}</g:link>
                    <small><cite title="Source Title">${threadInstance.firstPost.author.displayName}</cite></small>
                </blockquote>
            </div>
        </g:each>

    </div>
    <div class="col-md-4">

        <div class="">
            <h1>${message(code: 'home.tagList.label', default: 'See threads by tags')}</h1>
        </div>
        <div class="well">
            <g:link controller="tag" action="list" class="btn btn-success btn-lg btn-block">${message(code: 'home.tagList.all', default: 'See all tags')}</g:link>
            <g:each in="${tags}" status="i" var="tagInstance">
                <g:link controller="tag" action="show" id="${tagInstance.id}" class="btn btn-default btn-lg btn-block">
                ${tagInstance.name}
                </g:link>
            </g:each>
        </div>

    </div>
</div>
</body>
</html>